#########################################
#                                       #
# AUTOGENERATED BY SETUPKEYTOOL V1.0.03 #
#     THIS IS SENSITIVE INFORMATION     #
#       @ZockerKatze/@rattatwinko       #
#                                       #
#########################################

from tgtg import TgtgClient

# Don't ever give this Info to someone you dont trust!
# This is the Private Key to your TGTG Account

client = TgtgClient(access_token="asdf", refresh_token="asdf", cookie="asdf")
